# Generated by Django 4.1.2 on 2022-11-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_inbox_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
    ]
