# Generated by Django 4.1.2 on 2022-11-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
        ('inbox', '0004_remove_inbox_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
